services:
    rmcgirr83.noquoteintopic.listener:
        class: rmcgirr83\noquoteintopic\event\listener
        arguments:
            - @auth
            - @user
        tags:
            - { name: event.listener }
